name: 'deploy'

on:
  push:
    branches:
      - '**'

    tags:
      - '**'

env:
  DEV_PROJECT_ID: dev-project
  DEV_FB_PROJECT_ID: dev-project-fb
  PROD_PROJECT_ID: prod-project
  PROD_FB_PROJECT_ID: prod-project-fb

jobs:
 
  test-work:
    name: Test
    runs-on: ubuntu-latest
    steps:
     - name: check_PROD
       if:  contains(github.ref, 'main')
       run: |
            echo "this is ${{ github.ref}}"
            echo "env is ${{env.PROD_PROJECT_ID}}"

     - name: check_dev
       if:  contains(github.ref, 'dev')
       run: |
            echo "this is ${{ github.ref}}"
            echo "env is ${{env.DEV_PROJECT_ID}}"
    
