name: 'deploy'

on:
  push:
    branches:
      - '**'

    tags:
      - '**'

env:
  PROJECT_ID: yo
  FB_PROJECT_ID: "${{ github.ref }} === 'refs/heads/main' ? 'dhoom' : 'machale' "
  PROD: contains(github.ref, 'main') 

jobs:
 
  test-work:
    name: Test
    runs-on: ubuntu-latest
    steps:
     - name: check_PROD
       env:
        ENV_VAL: PROD
       run: |
          
            echo "this is ${{ github.ref}}"
            echo "env is ${{env.PROD}}"
    
