name: 'deploy'

on:
  push:
    branches:
      - '**'

    tags:
      - '**'

env:
  DEV_PROJECT_ID: dev-project
  DEV_FB_PROJECT_ID: dev-project-fb
  PROD_PROJECT_ID: prod-project
  PROD_FB_PROJECT_ID: prod-project-fb

jobs:
 
  test-work:
    name: Test
    runs-on: ubuntu-latest
    steps:
     - name: Lint Code Base
       uses: github/super-linter@v4
       env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          
     - name: check_PROD
       if:  contains(github.ref, 'main')
       run: |
            echo "this is ${{ github.ref}}"
            echo "env is ${{env.PROD_PROJECT_ID}}"

     - name: check_dev
       if:  github.ref == 'refs/heads/dev'
       run: |
            echo "this is ${{ github.ref}}"
            echo "env is ${{env.DEV_PROJECT_ID}}"

     - name: check_both
       if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
       run: |
            if [[ "${{ github.ref }}" == 'refs/heads/dev' ]]; then
              echo "dev hai"
            else
              echo "prod"
            fi
